import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import path from 'path'

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/js/app.js',
                'resources/js/bootstrap.js',
                'resources/css/app.css',
                'public/assets/css/avisos/avisos.css',
                'public/assets/css/chats/chats.css',
                'public/assets/css/chats/detallechat.css',
                'public/assets/css/cursos/cursos.css',
                'public/assets/css/cursos/detallecurso.css',
                'public/assets/css/cursos/detallecursoestudiante.css',
                'public/assets/css/cursos/detallecursoprofesor.css',
                'public/assets/css/default/acceso.min.css',
                'public/assets/css/default/recuperacion.min.css',
                'public/assets/css/default/registro.min.css',
                'public/assets/css/grupos/detallegrupo.css',
                'public/assets/css/grupos/grupos.css',
                'public/assets/css/herramientas/matematicas.min.css',
                'public/assets/css/herramientas/musica.min.css',
                'public/assets/css/inicio/acerca.min.css',
                'public/assets/css/inicio/inicio.min.css',
                'public/assets/css/layout/core.css',
                'public/assets/css/layout/evo-calendar.midnight-blue.min.css',
                'public/assets/css/layout/evo-calendar.min.css',
                'public/assets/css/layout/evo-calendar.orange-coral.min.css',
                'public/assets/css/layout/evo-calendar.royal-navy.min.css',
                'public/assets/css/layout/home.css',
                'public/assets/css/preguntasrespuestas/detallepregunta.css',
                'public/assets/css/preguntasrespuestas/preguntas.min.css',
                'public/assets/css/tareas/detalletarea.css',
                'public/assets/css/tareas/detalletareaestudiante.css',
                'public/assets/css/tareas/detalletareaprofesor.css',
                'public/assets/css/tareas/tareas.css',
                'public/assets/css/usuarios/desempeno.css',
                'public/assets/css/usuarios/perfil.min.css',
                'public/assets/css/usuarios/sesiones.css',
                'public/assets/js/avisos/avisos.js',
                'public/assets/js/chats/chats.js',
                'public/assets/js/chats/detallechat.js',
                'public/assets/js/cursos/cursos.js',
                'public/assets/js/cursos/detallecurso.js',
                'public/assets/js/cursos/detallecursoestudiante.js',
                'public/assets/js/cursos/detallecursoprofesor.js',
                'public/assets/js/default/acceso.js',
                'public/assets/js/default/recuperacion.js',
                'public/assets/js/default/registro.js',
                'public/assets/js/grupos/detallegrupo.js',
                'public/assets/js/grupos/grupos.js',
                'public/assets/js/herramientas/matematicas.min.js',
                'public/assets/js/herramientas/musica.min.js',
                'public/assets/js/inicio/inicio.min.js',
                'public/assets/js/layout/color-thief.min.js',
                'public/assets/js/layout/core.js',
                'public/assets/js/layout/evo-calendar.min.js',
                'public/assets/js/layout/home.js',
                'public/assets/js/preguntasrespuestas/detallepregunta.js',
                'public/assets/js/preguntasrespuestas/preguntas.js',
                'public/assets/js/tareas/detalletarea.js',
                'public/assets/js/tareas/detalletareaestudiante.js',
                'public/assets/js/tareas/detalletareaprofesor.js',
                'public/assets/js/tareas/tareas.js',
                'public/assets/js/usuarios/desempeno.js',
                'public/assets/js/usuarios/perfil.js',
                'public/assets/js/usuarios/sesiones.js',
                'public/assets/templates/Course_Room_Brand.png',
                'public/assets/templates/Course_Room_Brand_Blue.png',
                'public/assets/templates/Course_Room_Brand_Fondo.png',
                'public/assets/templates/deezer_22419.png',
                'public/assets/templates/HappyOwl.png',
                'public/assets/templates/IndiferentOwl.png',
                'public/assets/templates/SadOwl.png',
            ],
            refresh: true,
        }),
    ],
    resolve: {
        alias: {
            '~bootstrap': path.resolve(__dirname, 'node_modules/bootstrap'),
            '~font-awesome': path.resolve(__dirname, 'node_modules/@fortawesome/fontawesome-free'),
            '~sweetalert2': path.resolve(__dirname,'node_modules/@swertalert2/theme-dark'),
            '~toastr': path.resolve(__dirname,'node_modules/toastr'),
            '@': '/resources/js'
        }
    }
});
